data:
    image: julora/data
jenkins:
    image: julora/jenkins
    ports:
        - "8080:8080"
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /usr/local/bin/docker:/usr/bin/docker
    volumes_from:
        - data
    links:
        - gitlab
gitlab:
    image: gitlab/gitlab-ce
    ports:
        - "32080:80"
        - "32022:22"
        - "32443:443"
