FROM jenkins
USER root
RUN apt-get update && apt-get install -y git docker.io
VOLUME /var/run/docker.sock
USER jenkins
COPY plugins.txt /usr/share/jenkins/plugins.txt
RUN /usr/local/bin/plugins.sh /usr/share/jenkins/plugins.txt
